<?php

namespace App\Support;

use Illuminate\Foundation\Vite;
use Illuminate\Support\HtmlString;

final class ProjectVite
{
    public function __construct(private readonly Vite $vite)
    {
    }

    /**
     * Render Vite asset tags for development and production.
     *
     * Local requests use the Vite dev server when it is running. All other
     * environments always resolve the versioned files in the build manifest
     * generated by `npm run build`.
     *
     * @param  array<int, string>  $entrypoints
     */
    public function tags(array $entrypoints): HtmlString
    {
        if (app()->isLocal()) {
            return ($this->vite)($entrypoints);
        }

        // `public/hot` is only valid on a developer machine. Use a non-existent
        // hot-file path in deployed environments so a stray hot file cannot
        // point visitors to a local Vite server.
        $vite = clone $this->vite;
        $vite->useHotFile(storage_path('framework/vite.hot'));

        return $vite($entrypoints);
    }
}
